package br.com.petscare.petscare.model;

public class Arrays {
    public static String[] racasCachorro = {"Afghan Hound",
            "Airedale Terrier",
            "Akita",
            "American Staffordshire Terrier",
            "Australian Cattle Dog",
            "Banseji",
            "Basset Hound",
            "Beagle",
            "Bernese Mountain",
            "Bichon Frise",
            "Bloodhound",
            "Border Collie",
            "Borzoi",
            "Boston Terriers",
            "Boxer",
            "Bull Terrier",
            "Bulldog Frances",
            "Bulldog Ingles",
            "Cane Corso",
            "Cao de crista Chines",
            "Cavalier King Charles Spaniel",
            "Chihuahua",
            "Chow Chow",
            "Cocker Spaniel",
            "Collie",
            "Dalmata",
            "Doberman",
            "Dogo Argentino",
            "Dogue Alemao",
            "Dogue de Bordeaux",
            "Fila Brasileiro",
            "Fox Paulistinha",
            "Goldens",
            "Greyhound",
            "Griffon de Bruxelas",
            "Husky Siberiano",
            "Jack Russel",
            "Kuvasz",
            "Labrador",
            "Leao da Rodesia",
            "Lhasa Apso",
            "Lulu da Pomerania",
            "Malamute do Alasca",
            "Maltes",
            "Mastiff",
            "Papillon",
            "Pastor Alemao",
            "Pastor Australiano",
            "Pastor Belga",
            "Pastor Branco Suico",
            "Pastor Maremano",
            "Pastor de Shetland",
            "Pequines",
            "Pinscher",
            "Pit Bull",
            "Pointer",
            "Poodle",
            "Pug",
            "Rottweiler",
            "Samoieda",
            "Sao Bernardo",
            "Schnauzer Miniatura",
            "Setter irlandes",
            "Shar Pei",
            "Sheepdog",
            "Shiba",
            "Shih Tzu",
            "Spitz Japones",
            "Staffordshire Bull Terrier",
            "Teckel",
            "Weimaraner",
            "Welsh Corgi Cardigan",
            "Welsh Corgi Pembroke",
            "Westie",
            "Whippet",
            "Yorkshire Terrier"};

    public static String[] racasGatos = {"Abissinio",
            "American Shorthair",
            "Angora",
            "Azul Russo",
            "Bengal",
            "Birmanes",
            "Brazilian Shorthair",
            "British Shorthair",
            "Burmese",
            "Chartreux",
            "Cornish Rex",
            "Devon Rex",
            "Egyptian Mau",
            "European Shorthair",
            "Exotico",
            "Himalaio",
            "Maine Coon",
            "Munchkin",
            "Norwegian Forest",
            "Oriental",
            "Persa",
            "Ragdoll",
            "Savannah",
            "Scottish Fold",
            "Siames",
            "Sphynx"};

    public static String[] iconesGato = {};

    public static String[] iconesCachorro = {};

    public static String[] bannerGato = {"bg0",
            "bg1",
            "bg2",
            "bg3",
            "bg4",
            "bg5",
            "bg6",
            "bg7",
            "bg8",
            "bg9",
            "bg10",
            "bg11",
            "bg12",
            "bg13",
            "bg14",
            "bg15",
            "bg16",
            "bg17",
            "bg18",
            "bg19",
            "bg20",
            "bg21",
            "bg22",
            "bg23",
            "bg24",
            "bg25",
            "bg26"};

    public static String[] bannerCachorro = {"gc0",
            "gc1",
            "gc2",
            "gc3",
            "gc4",
            "gc5",
            "gc6",
            "gc7",
            "gc8",
            "gc9",
            "gc10",
            "gc11",
            "gc12",
            "gc13",
            "gc14",
            "gc15",
            "gc16",
            "gc17",
            "gc18",
            "gc19",
            "gc20",
            "gc21",
            "gc22",
            "gc23",
            "gc24",
            "gc25",
            "gc26",
            "gc27",
            "gc28",
            "gc29",
            "gc30",
            "gc31",
            "gc32",
            "gc33",
            "gc34",
            "gc35",
            "gc36",
            "gc37",
            "gc38",
            "gc39",
            "gc40",
            "gc41",
            "gc42",
            "gc43",
            "gc44",
            "gc45",
            "gc46",
            "gc47",
            "gc48",
            "gc49",
            "gc50",
            "gc51",
            "gc52",
            "gc53",
            "gc54",
            "gc55",
            "gc56",
            "gc57",
            "gc58",
            "gc59",
            "gc60",
            "gc61",
            "gc62",
            "gc63",
            "gc64",
            "gc65",
            "gc66",
            "gc67",
            "gc68",
            "gc69",
            "gc70",
            "gc71",
            "gc72",
            "gc73",
            "gc74",
            "gc75",
            "gc76"};

    private Arrays(){}
}
